# Generated by Django 3.1.3 on 2022-01-25 08:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_sendgrid_parse', '0009_auto_20170221_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachment_info',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Attachment Info'),
        ),
        migrations.AddField(
            model_name='email',
            name='content_ids',
            field=models.CharField(blank=True, max_length=255, verbose_name='Content ids'),
        ),
        migrations.AddField(
            model_name='email',
            name='sender_ip',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sender ip'),
        ),
    ]
